POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1RFUjMiLCJpZCI6IjVjNWM1ZDBlMzgzMTlmM2VmMTg3YzJkZiIsImlhdCI6MTU0OTU2MjE5Mn0.kbLj_shUrYzzyw-ToEtowCXLagangGEyO1770aGALxw

{
    "title": "Hello World",
    "author": "Matti Meikäläinen",
    "url": "www.fi",
    "likes": 5
}