PUT http://localhost:3003/api/blogs/5c5c3a06f08ad62510e51953
Content-Type: application/json

    {
        "id": "5c5c3a06f08ad62510e51953",
        "title": "React patterns UPDATED",
        "author": "Michael Chan",
        "url": "https://reactpatterns.com/",
        "likes": 25
    }